all:
	gcc mm1.c -o output/mm1 -O0 -lpapi -static
	gcc mm2.c -o output/mm2 -O0 -lpapi -static
	gcc mm3.c -o output/mm3 -O0 -lpapi -static
	gcc mm4.c -o output/mm4 -O0 -lpapi -static
	gcc mm5.c -o output/mm5 -O0 -lpapi -static
	gcc mm6.c -o output/mm6 -O0 -lpapi -static
	gcc mm7.c -o output/mm7 -O0 -lpapi -static
	gcc mm8.c -o output/mm8 -O0 -lpapi -static
	gcc mm9.c -o output/mm9 -O0 -lpapi -static
	gcc mm10.c -o output/mm10 -O0 -lpapi -static
	
run:
	./output/mm1 0 >> wynik0
	./output/mm2 0 >> wynik0
	./output/mm3 0 >> wynik0
	./output/mm4 0 >> wynik0
	./output/mm5 0 >> wynik0
	./output/mm6 0 >> wynik0
	./output/mm7 0 >> wynik0
	./output/mm8 0 >> wynik0
	./output/mm9 0 >> wynik0
	./output/mm10 0 >> wynik0
	./output/mm1 1 >> wynik1
	./output/mm2 1 >> wynik1
	./output/mm3 1 >> wynik1
	./output/mm4 1 >> wynik1
	./output/mm5 1 >> wynik1
	./output/mm6 1 >> wynik1
	./output/mm7 1 >> wynik1
	./output/mm8 1 >> wynik1
	./output/mm9 1 >> wynik1
	./output/mm10 1 >> wynik1
	./output/mm1 2 >> wynik2
	./output/mm2 2 >> wynik2
	./output/mm3 2 >> wynik2
	./output/mm4 2 >> wynik2
	./output/mm5 2 >> wynik2
	./output/mm6 2 >> wynik2
	./output/mm7 2 >> wynik2
	./output/mm8 2 >> wynik2
	./output/mm9 2 >> wynik2
	./output/mm10 2 >> wynik2
	./output/mm1 3 >> wynik3
	./output/mm2 3 >> wynik3
	./output/mm3 3 >> wynik3
	./output/mm4 3 >> wynik3
	./output/mm5 3 >> wynik3
	./output/mm6 3 >> wynik3
	./output/mm7 3 >> wynik3
	./output/mm8 3 >> wynik3
	./output/mm9 3 >> wynik3
	./output/mm10 3 >> wynik3
	./output/mm1 4 >> wynik4
	./output/mm2 4 >> wynik4
	./output/mm3 4 >> wynik4
	./output/mm4 4 >> wynik4
	./output/mm5 4 >> wynik4
	./output/mm6 4 >> wynik4
	./output/mm7 4 >> wynik4
	./output/mm8 4 >> wynik4
	./output/mm9 4 >> wynik4
	./output/mm10 4 >> wynik4
